CREATE DATABASE IF NOT EXISTS SOS_NAME;
GRANT ALL ON *.* TO 'SOS_USER' IDENTIFIED BY 'SOS_PASSWORD' WITH GRANT OPTION;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'SOS_ROOT_PASSWORD';
FLUSH PRIVILEGES;